//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once


namespace winrt::Youtube_Caption_XAML_UI::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    class SearchUrlPageT : public ::winrt::Youtube_Caption_XAML_UI::implementation::SearchUrlPage_base<D,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector2,
        I...>
    {
    public:
        void InitializeComponent();
        void Connect(int32_t connectionId, IInspectable const& target);
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Windows::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Windows::UI::Xaml::Controls::TextBox UrlBox()
        {
            return _UrlBox;
        }
        void UrlBox(::winrt::Windows::UI::Xaml::Controls::TextBox value)
        {
            _UrlBox = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button Button()
        {
            return _Button;
        }
        void Button(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _Button = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock ResultsBlock()
        {
            return _ResultsBlock;
        }
        void ResultsBlock(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _ResultsBlock = value;
        }
        
    private:
        bool _contentLoaded{false};

        ::winrt::Windows::UI::Xaml::Controls::TextBox _UrlBox{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _Button{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _ResultsBlock{nullptr};
    };
}

