//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once


namespace winrt::Youtube_Caption_XAML_UI::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    class SearchUrlPageT : public ::winrt::Youtube_Caption_XAML_UI::implementation::SearchUrlPage_base<D,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector2,
        I...>
    {
    public:
        void InitializeComponent();
        void Connect(int32_t connectionId, IInspectable const& target);
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Windows::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Windows::UI::Xaml::Controls::StackPanel titleSearch()
        {
            return _titleSearch;
        }
        void titleSearch(::winrt::Windows::UI::Xaml::Controls::StackPanel value)
        {
            _titleSearch = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Image title()
        {
            return _title;
        }
        void title(::winrt::Windows::UI::Xaml::Controls::Image value)
        {
            _title = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::StackPanel searchBar()
        {
            return _searchBar;
        }
        void searchBar(::winrt::Windows::UI::Xaml::Controls::StackPanel value)
        {
            _searchBar = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Image thumbnail()
        {
            return _thumbnail;
        }
        void thumbnail(::winrt::Windows::UI::Xaml::Controls::Image value)
        {
            _thumbnail = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::StackPanel buttonStack()
        {
            return _buttonStack;
        }
        void buttonStack(::winrt::Windows::UI::Xaml::Controls::StackPanel value)
        {
            _buttonStack = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock mostFrequentBox()
        {
            return _mostFrequentBox;
        }
        void mostFrequentBox(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _mostFrequentBox = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock ResultsBlock()
        {
            return _ResultsBlock;
        }
        void ResultsBlock(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _ResultsBlock = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button searchWordsButton()
        {
            return _searchWordsButton;
        }
        void searchWordsButton(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _searchWordsButton = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button mostFrequentButton()
        {
            return _mostFrequentButton;
        }
        void mostFrequentButton(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _mostFrequentButton = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button testButton()
        {
            return _testButton;
        }
        void testButton(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _testButton = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBox UrlBox()
        {
            return _UrlBox;
        }
        void UrlBox(::winrt::Windows::UI::Xaml::Controls::TextBox value)
        {
            _UrlBox = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button Button()
        {
            return _Button;
        }
        void Button(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _Button = value;
        }
        
    private:
        bool _contentLoaded{false};

        ::winrt::Windows::UI::Xaml::Controls::StackPanel _titleSearch{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Image _title{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::StackPanel _searchBar{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Image _thumbnail{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::StackPanel _buttonStack{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _mostFrequentBox{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _ResultsBlock{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _searchWordsButton{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _mostFrequentButton{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _testButton{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBox _UrlBox{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _Button{nullptr};
    };
}

