// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.0.h"
#include "winrt/impl/Youtube_Caption_XAML_UI.0.h"

WINRT_EXPORT namespace winrt::Youtube_Caption_XAML_UI {

struct WINRT_EBO IMainPage :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMainPage>
{
    IMainPage(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISearchPage2 :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISearchPage2>
{
    ISearchPage2(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISearchUrlPage :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISearchUrlPage>
{
    ISearchUrlPage(std::nullptr_t = nullptr) noexcept {}
};

}
